name: Generate Requirements and Build EXEs

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate requirements.txt
        run: |
          echo "Collecting requirements from .py files..."
          (Get-Content *.py | Select-String -Pattern '^(from|import) (\w+)' -AllMatches | ForEach-Object { $_.Matches.Groups[2].Value } | Sort-Object -Unique) > requirements.txt
          echo "Generated requirements.txt with the following content:"
          type requirements.txt

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install -r requirements.txt || echo "Warning: Some packages could not be installed, but the process will continue."

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executables
        run: |
          Get-ChildItem -Path . -Filter *.py | ForEach-Object {
            pyinstaller --onefile $_.Name
          }

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
